### ISSUE TITLE
eBee spotted: Bulldozer (sidecar-less) eBee

### ISSUE THREAD

**Issue by qmonnet** [isovalent/ebeedex#45]
![bulldozer-bee](https://user-images.githubusercontent.com/17001771/232012308-05110abd-0de8-4963-9135-0711e0200035.png)

Can't remember what blog or presentation this was for, though.

Not a very “neutral” one, so not sure if fit for the eBeeDex.

**Comment by jspaleta** [comment]
We could clean it up and remove the "sidecar proxy" text and make the bee more general?
