### ISSUE TITLE
eBee spotted: Hiking eBee

### ISSUE THREAD

**Issue by qmonnet** [isovalent/ebeedex#70]
![image](https://github.com/isovalent/ebeedex/assets/17001771/f6c5128f-fe40-4013-840f-6e5a45486b70)

Exploring the Swiss mountains

**Comment by jgcolvin-iso** [comment]
Backstory: 

Armed with a backpack filled with snacks and a sense of adventure, the Hiking eBee is always on the lookout for peak experiences. This eBee is no stranger to challenges. They carefully navigate rocky paths, leap across babbling streams, and scale steep cliffs, always driven by an unwavering appreciation for the outdoors. Along the way, they encounter fellow creatures of the mountain, from chirping birds to inquisitive squirrels, forging connections and cherishing the natural world. As they navigate challenging paths and form bonds with the mountain’s residents, they find kindred spirits among their fellow eBees, like the tech-savvy Electrician eBee, who illuminates their night hikes with digital lanterns.

Also added a PR for version without the Mountain background
