### ISSUE TITLE
eBee spotted: Sledding eBee

### ISSUE THREAD

**Issue by qmonnet** [isovalent/ebeedex#71]
![](https://github.com/isovalent/ebeedex/assets/17001771/c6a4be5e-8b0a-4411-8153-86b82f669f95)

**Comment by xmulligan** [comment]
Is this from the off-site? Or an office?

**Comment by qmonnet** [comment]
Spotted in the Zurich office. No idea what it was designed for, or who has the sources :disappointed:.

**Comment by xmulligan** [comment]
![1](https://github.com/isovalent/ebeedex/assets/29048870/27b88500-092f-47ff-8de5-c743e99dcf2a)
![1](https://github.com/isovalent/ebeedex/assets/29048870/f85e88fa-460a-4710-9112-05f9b7f8a825)
here are the originals
